#################################################################
#                                                               #
#             Home Assistant NEW configuration file             #
#                                                               #
#             Created: 2020.09.20                               #
#                                                               #
#################################################################
  
# default config
# =============
# Configure a default setup of Home Assistant (frontend, api, etc)
# - https://www.home-assistant.io/integrations/default_config/ for all the integrations loaded by this setting.
default_config:


# frontend
# ========
# Enables the frontend to define themes
# - https://www.home-assistant.io/integrations/frontend/#defining-themes
# 2022.01.05
# - use include_dir_merge_named to include all the themes. Move name of theme also to theme file itself,
#   instead of in themes.yaml (deprecated now).
  # themes: !include themes/themes.yaml
frontend:
  themes: !include_dir_merge_named themes/
  
# hacs settings
# =============
# - https://hacs.xyz/docs/installation/manual
#
# 2019.07.19
# - Add HACS instead of custom updater
hacs:
  token: !secret hacs_token
  sidepanel_title: "Store" 
  sidepanel_icon: "mdi:alpha-c-box"
  theme: true
  appdaemon: true
  python_script: true

# lovelace 
# ========
# - https://www.home-assistant.io/lovelace/dashboards-and-views/
#
# 2019.08.02
# Switch lovelace to yaml mode again, so I can use includes and reuse stuff
# But also, make it much more manageble with include per view
#
# 2021.01.15
# Move resource include from ui-lovelace.yaml to configuration.
lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml

  dashboards:
    sak-examples:
      mode: yaml
      filename: sak-examples-dashboard.yaml
      title: Swiss Army Knife Examples
      icon: mdi:hospital-box
      show_in_sidebar: true
      
