#################################################################
#                                                               # 
#             Home Assistant NEW Lovelace configuration         #
#                                                               #
#             Created: 2020.09.20                               #
#                                                               #
#################################################################
  
# Include custom cards / tools and plugins for lovelace.
#
# resources:
# 
  
# Decluttering Templates
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

# Swiss Army Knife Templates
sak_templates:
  !include lovelace/sak_templates/sak_templates.yaml

title: ZoefDeHaas
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.back_door_contact
      - entity: binary_sensor.kitchen_light_fridge_update_available
      - entity: binary_sensor.livingroom_light_gasheater_update_available
      - entity: binary_sensor.livingroom_light_front_right_update_available
      - entity: binary_sensor.backyard_light_backdoor_update_available
      - entity: binary_sensor.livingroom_light_couch_tv_right_update_available

      - entity: sensor.back_door_battery
      - entity: sensor.back_door_linkquality
      - entity: sensor.doorbell_vibration_action
      - entity: sensor.doorbell_vibration_battery
      - entity: sensor.doorbell_vibration_linkquality
      - entity: sensor.doorbell_vibration_sensitivity
      - entity: sensor.doorbell_vibration_strength
      - entity: sensor.studym_iaq_temperature
      - entity: sensor.studym_iaq_humidity
      - entity: sensor.studym_iaq_pressure
      - entity: sensor.studym_iaq_battery
      - entity: sensor.studym_iaq_linkquality
      - entity: sensor.bedroom_iaq_temperature
      - entity: sensor.bedroom_iaq_humidity
      - entity: sensor.bedroom_iaq_pressure
      - entity: sensor.bedroom_iaq_battery
      - entity: sensor.bedroom_iaq_linkquality
      - entity: sensor.kitchen_iaq_temperature
      - entity: sensor.kitchen_iaq_humidity 
      - entity: sensor.kitchen_iaq_pressure
      - entity: sensor.kitchen_iaq_battery
      - entity: sensor.kitchen_iaq_linkquality
      - entity: sensor.bathroom_iaq_temperature
      - entity: sensor.bathroom_iaq_humidity
      - entity: sensor.bathroom_iaq_pressure
      - entity: sensor.bathroom_iaq_battery
      - entity: sensor.bathroom_iaq_linkquality
      - entity: sensor.hall_gf_iaq_temperature
      - entity: sensor.hall_gf_iaq_humidity
      - entity: sensor.hall_gf_iaq_pressure
      - entity: sensor.hall_gf_iaq_battery
      - entity: sensor.hall_gf_iaq_linkquality
      - entity: sensor.studyf_iaq_temperature
      - entity: sensor.studyf_iaq_humidity
      - entity: sensor.studyf_iaq_pressure
      - entity: sensor.studyf_iaq_battery
      - entity: sensor.studyf_iaq_linkquality
      - entity: sensor.kitchen_light_fridge_linkquality
      - entity: sensor.backyard_light_backdoor_linkquality
      - entity: sensor.livingroom_light_couch_tv_left_linkquality
      - entity: sensor.livingroom_light_gasheater_linkquality
      - entity: sensor.livingroom_light_front_right_linkquality
      - entity: sensor.livingroom_light_cupboard_linkquality
      - entity: sensor.livingroom_light_couch_tv_right_linkquality
      - entity: sensor.dafang3_light_sensor
      - entity: sensor.hacs
      - entity: sun.sun
    cards:
      - type: picture-entity
        entity: camera.dafang3_motion_snapshot
      - type: entities
        entities:
          - cover.dafang3_move_left_right
          - cover.dafang3_move_up_down
        title: Cover
      - type: entities
        entities:
          - light.1st_floor_hall_light
          - light.backyard_light_backdoor_light
          - light.kitchen_light_fridge_light
          - light.livingroom_light_couch_tv_left_light
          - light.livingroom_light_couch_tv_right_light
          - light.livingroom_light_cupboard_light
          - light.livingroom_light_front_right_light
          - light.livingroom_light_gasheater_light
        title: Light
      - type: media-control
        entity: media_player.huiskamer
      - type: entities
        entities:
          - switch.dafang3_blue_led
          - switch.dafang3_h264_rtsp_server
          - switch.dafang3_ir_filter
          - switch.dafang3_ir_led
          - switch.dafang3_mjpeg_rtsp_server
          - switch.dafang3_motion_detection
          - switch.dafang3_motion_send_mail
          - switch.dafang3_motion_tracking
          - switch.dafang3_night_mode
          - switch.dafang3_night_mode_auto
          - switch.dafang3_w_led
        title: Switch
      - type: weather-forecast
        entity: weather.zoefdehaas
      - type: entities
        entities:
          - zigbee2mqtt_networkmap.map_last_update
        title: zigbee2mqtt Networkmap

  - title: Energie        
    icon: 'mdi:flash'
    id: view_energy
    path: energy
    cards:
      - !include lovelace/views/cards-energy.yaml

  - title: Verwarming
    id: view_heating
    icon: ''
    path: heating
    cards:
      - !include lovelace/views/cards-heating.yaml

# Testing 1-2-3-4-5-6

  ## If this view is included, sak  is called TWICE!!!!!!!! OR not ???? F5 also generates something
  ## No seems F5. Switching panels doesn't do the double calls, only F5
  # - title: Vering
    # icon: 'mdi:lightbulb'
    # id: view_lights
    # path: lights
    # cards:
      # !include lovelce/views/cards-lights-mw.yaml

  - title: sak-lights
    icon: 'mdi:thermometer'
    id: view_sak_airquality
    path: sakiaq
    cards:
      !include lovelace/views/cards-air-quality-mw.yaml

  - title: sak-lights
    icon: 'mdi:lightbulb'
    id: view_sak_lights
    path: saklights
    cards:
      !include lovelace/views/cards-lights-sak.yaml

  - title: sak-lights-nm
    icon: 'mdi:lightbulb'
    id: view_sak_lights_nm
    path: saklights_nm
    cards:
      !include lovelace/views/cards-lights-sak-nm.yaml

  - !include lovelace/views/view-servers.yaml
  # - !include lovelace/views/view-laundry.yaml
  # - !include lovelace/views/view-security.yaml
  
  # Swiss Army Knife test views...
  - !include lovelace/views/view-sakt1.yaml         # SAKT1
  - !include lovelace/views/view-sakt2.yaml

  # # Swiss Army Knife example views...
  # - !include lovelace/views/view-sake1.yaml
  # - !include lovelace/views/view-sake2.yaml
  # - !include lovelace/views/view-sake3.yaml
  # - !include lovelace/views/view-sake4.yaml
  # - !include lovelace/views/view-sake5.yaml
  # - !include lovelace/views/view-sake6.yaml
  # - !include lovelace/views/view-sake7.yaml
  # - !include lovelace/views/view-sake8.yaml

  # Horseshoe examples
  - !include lovelace/views/view-flex-horseshoe-card-examples.yaml

#  - !include lovelace/views/view-wip.yaml

#  - !include lovelace/views/view-wip2.yaml

  # - !include lovelace/views/view-fhce.yaml

  - !include lovelace/views/view-flce-small.yaml

