sak_layout_fce_environment:
  template:
    type: layout
    defaults: 
      - var_entity_index: 0
  layout:
    aspectratio: 6/1                          # Card is 600x100 grid
    styles:
      card:
    toolsets:
      # ================================================================
      - toolset: line1
        position:
          cx: 200
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: line
            position:
              cx: 50
              cy: 50
              orientation: vertical
              length: 50
            styles:
              line:
                fill: var(--primary-text-color)
                opacity: 0.5

      # ================================================================
      - toolset: line2
        position:
          cx: 500
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: line
            position:
              cx: 50
              cy: 50
              orientation: vertical
              length: 50
            styles:
              line:
                fill: var(--primary-text-color)
                opacity: 0.5


      # ================================================================
      - toolset: half-circle
        position:
          cx: 0                             # Center on cards border 
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: circle
            position:
              cx: 50
              cy: 50
              radius: 48
            styles:
              circle:
                fill: none
                stroke: var(--theme-sys-color-secondary)
                stroke-width: 3em
                opacity: 0.5

        # ================================================================
      - toolset: column-icon
        position:
          cx: 25
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: icon
            position:
              cx: 50
              cy: 50
              align: center
              icon_size: 30
            entity_index: 0
            styles:
              icon:
                fill: var(--theme-sys-color-secondary)
              
      - toolset: column-name
        position:
          cx: 120
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: name
            position:
              cx: 50
              cy: 50
            entity_index: 0
            styles:
              name:
                text-anchor: middle
                font-size: 25em
                font-weight: 700
                opacity: 1

          # ------------------------------------------------------------
          - type: state
            position:
              cx: 50
              cy: 80
            entity_index: 5
            show:
              uom: none
            styles:
              state:
                text-anchor: middle
                font-size: 14em
                font-weight: 500
                opacity: 0.7

      # ================================================================
      - toolset: column-temperature
        position:
          cx: 260
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: icon
            position:
              cx: 50
              cy: 30
              align: center
              icon_size: 25
            entity_index: 5
            styles:
              icon:
                fill: var(--theme-sys-color-secondary)

          # ------------------------------------------------------------
          - type: state
            position:
              cx: 50
              cy: 55
            entity_index: 0
            show:
              uom: bottom
            styles:
              state:
                text-anchor: middle
                font-size: 20em
                font-weight: 700
                fill: var(--primary-text-color)
              uom:
                fill: var(--primary-text-color)
                font-weight: 700

          # ------------------------------------------------------------ 
          - type: 'segarc'
            id: 0
            position:
              cx: 50
              cy: 50
              start_angle: 0
              end_angle: 360
              width: 6
              radius: 40
            entity_index: 0
            scale:
              min: 15
              max: 25
              width: 6
              offset: 12
            show:
              scale: false
              style: 'colorlist'
            segments:
              colorlist:
                gap: 1
                colors:
                  - var(--theme-sys-palette-primary50)
            styles:
              foreground:
                fill: darkgrey
              background:
                fill: var(--theme-sys-elevation-surface-neutral4)
                opacity: 1

      # ================================================================
      - toolset: column-humidity
        position:
          cx: 355
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: icon
            position:
              cx: 50
              cy: 30
              align: center
              icon_size: 25
            entity_index: 1
            styles:
              icon:
                fill: var(--theme-sys-color-secondary)

          # ------------------------------------------------------------
          - type: state
            position:
              cx: 50
              cy: 55
            entity_index: 1
            show:
              uom: bottom
            styles:
              state:
                text-anchor: middle
                font-size: 20em
                font-weight: 700
                fill: var(--primary-text-color)
              uom:
                fill: var(--primary-text-color)
                font-weight: 700

          # ------------------------------------------------------------ 
          - type: 'segarc'
            id: 0
            position:
              cx: 50
              cy: 50
              start_angle: 0
              end_angle: 360
              width: 6
              radius: 40
            entity_index: 1
            scale:
              min: 0
              max: 100
              width: 6
              offset: 12
            show:
              scale: false
              style: 'colorlist'
            segments:
              colorlist:
                gap: 1
                colors:
                  - var(--theme-sys-palette-primary45)
            styles:
              foreground:
                fill: darkgrey
              background:
                fill: var(--theme-sys-elevation-surface-neutral4)
                opacity: 1

      # ================================================================
      - toolset: column-pressure
        position:
          cx: 450
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: icon
            position:
              cx: 50
              cy: 30
              align: center
              icon_size: 25
            entity_index: 2
            styles:
              icon:
                fill: var(--theme-sys-color-secondary)

          # ------------------------------------------------------------
          - type: state
            position:
              cx: 50
              cy: 55
            entity_index: 2
            show:
              uom: bottom
            styles:
              state:
                text-anchor: middle
                font-size: 20em
                font-weight: 700
                fill: var(--primary-text-color)
              uom:
                fill: var(--primary-text-color)
                font-weight: 700

          # ------------------------------------------------------------ 
          - type: 'segarc'
            id: 0
            position:
              cx: 50
              cy: 50
              start_angle: 0
              end_angle: 360
              width: 6
              radius: 40
            entity_index: 2
            scale:
              min: 950
              max: 1050
              width: 6
              offset: 12
            show:
              scale: false
              style: 'colorlist'
            segments:
              colorlist:
                gap: 1
                colors:
                  - var(--theme-sys-palette-primary40)
            styles:
              foreground:
                fill: darkgrey
              background:
                fill: var(--theme-sys-elevation-surface-neutral4)
                opacity: 1

      # ================================================================
      - toolset: column-battery
        position:
          cx: 540
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: icon
            position:
              cx: 30
              cy: 30
              align: right
              icon_size: 25
            entity_index: 3
            styles:
              icon:
                fill: var(--theme-sys-color-tertiary)
                opacity: 0.8

          # ------------------------------------------------------------
          - type: state
            position:
              cx: 70
              cy: 30
            entity_index: 3
            show:
              uom: none
            styles:
              state:
                text-anchor: middle
                font-size: 15em
                font-weight: 700
                fill: var(--primary-text-color)
              uom:
                fill: var(--primary-text-color)
                font-weight: 700

          # ------------------------------------------------------------ 
          - type: 'segarc'
            id: 0
            position:
              cx: 70
              cy: 30
              start_angle: 0
              end_angle: 360
              width: 3
              radius: 18
            entity_index: 3
            scale:
              min: 0
              max: 100
              width: 6
              offset: 12
            show:
              scale: false
              style: 'colorlist'
            segments:
              colorlist:
                gap: 1
                colors:
                  - var(--theme-sys-palette-tertiary45)
            styles:
              foreground:
                fill: darkgrey
              background:
                fill: var(--theme-sys-elevation-surface-neutral4)
                opacity: 1

      # ================================================================
      - toolset: column-linkquality
        position:
          cx: 540
          cy: 50
        tools:
          # ------------------------------------------------------------
          - type: icon
            position:
              cx: 30
              cy: 70
              align: right
              icon_size: 25
            entity_index: 4
            styles:
              icon:
                fill: var(--theme-sys-color-tertiary)
                opacity: 0.8

          # ------------------------------------------------------------
          - type: state
            position:
              cx: 70
              cy: 70
            entity_index: 4
            show:
              uom: none
            styles:
              state:
                text-anchor: middle
                font-size: 15em
                font-weight: 700
                fill: var(--primary-text-color)
              uom:
                fill: var(--primary-text-color)
                font-weight: 700

          # ------------------------------------------------------------ 
          - type: 'segarc'
            id: 0
            position:
              cx: 70
              cy: 70
              start_angle: 0
              end_angle: 360
              width: 3
              radius: 18
            entity_index: 4
            scale:
              min: 0
              max: 100
              width: 6
              offset: 12
            show:
              scale: false
              style: 'colorlist'
            segments:
              colorlist:
                gap: 1
                colors:
                  - var(--theme-sys-palette-tertiary45)
            styles:
              foreground:
                fill: darkgrey
              background:
                fill: var(--theme-sys-elevation-surface-neutral4)
                opacity: 1
