#automation:

  - alias: Er is op de deurbel gedrukt
    id: doorbell_vibration_automation
    initial_state: 'on' 
    trigger:
      platform: state
      entity_id: sensor.doorbell_vibration_action
      to: 'vibration'
    action:
      service: notify.ios_iphone_van_marco
      data:
        title: "Domus Waarschuwing"
        message: "Er staat iemand voor de deur!"
            
  - alias: 'Lampen woonkamer aan voor zonsondergang'
    id: livingroom_lights_on_before_sunset_automation
    initial_state: 'on' 
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
    action:
      service: homeassistant.turn_on
      entity_id: group.livingroom_lights

  - alias: 'Lampen keuken aan voor zonsondergang'
    id: kitchen_lights_on_before_sunset_automation
    initial_state: 'on' 
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 1.5
    action:
      service: homeassistant.turn_on
      entity_id: group.kitchen_lights

  - alias: 'Lampen buiten aan na zonsondergang'
    id: outside_lights_on_after_sunset_automation
    initial_state: 'on' 
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -1.5
    action:
      service: homeassistant.turn_on
      entity_id: group.outside_lights

  - alias: 'Lampen buiten uit na zonsopgang'
    id: outside_lights_off_after_sunrise_automation
    initial_state: 'on' 
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: -1.5
    action:
      service: homeassistant.turn_off
      entity_id: group.outside_lights
      
# Sonoffs settings
# See: https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant

  - alias: "Enable MQTT discovery for all devices"
    id: sonoffs_enable_mqtt_discovery_automation
    initial_state: 'on' 
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/SetOption55"
          payload: "1"
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/SetOption19"
          payload: "1"
          
  - alias: "Power state on HA start-up"
    id: sonoffs_power_state_automation
    initial_state: 'on' 
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/state"
          payload: ""

  - alias: "Power state on HA start-up 2"
    id: sonoffs_power_state2_on_automation
    initial_state: 'on' 
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "sonoffs/cmnd/state"
          payload: ""          

  - id: update_networkmap
    alias: 'Zigbee Map Refresh'  
    # hide_entity: true  
    initial_state: 'on' 
    trigger:
      platform: time_pattern
      minutes: 00 #'/10'
      seconds: 00
    action:
      service: zigbee2mqtt_networkmap.update          